### ISSUE TITLE
Can't find sw.json file

### ISSUE THREAD

**Issue by nhatminh-it** [jojo96/Chatterbot-Streamlit#1]
Hello,
I read your code and found sw.json in line 13, but I can't find it in your dataset. Could you please help me?
Thanks

**Comment by jojo96** [comment]
> Hello,
> I read your code and found sw.json in line 13, but I can't find it in your dataset. Could you please help me?
> Thanks

Hi, added the sw.json file: https://github.com/jojo96/Chatterbot-Streamlit/blob/master/sw.json

**Comment by nhatminh-it** [comment]
Thank you
